import { StyleSheet } from 'react-native';

export const colors = { primary: '#087CF0', primaryDark: '#071A63', background: '#F7FBFF', surface: '#FFFFFF', surfaceBlue: '#EDF7FF', surfaceSoft: '#F2F8FD', border: '#D8EAF7', text: '#071A63', textPrimary: '#071A63', secondary: '#55719A', textSecondary: '#55719A', muted: '#7F98B8', accent: '#087CF0', newziBlue: '#69B7F4', danger: '#CF6570', dangerSurface: '#FFF0F2', success: '#138A62', successSurface: '#EAF8F2', warning: '#A86D12', warningSurface: '#FFF6E7', shadow: { color: '#496B99', opacity: 0.1, radius: 12, offset: { width: 0, height: 4 } } };
export const spacing = { xs: 4, sm: 8, md: 12, lg: 16, xl: 20, xxl: 24, xxxl: 32, huge: 40 };
export const radius = { sm: 10, md: 14, lg: 20, pill: 999 };
export const iconSize = { sm: 16, md: 20, lg: 24, xl: 28 };
export const typography = { display: 36, h1: 32, h2: 24, h3: 18, body: 16, bodySmall: 14, caption: 12, button: 16, lineHeight: 24, fontFamily: { ui: 'Inter', editorial: 'Newsreader' } };
export const elevation = { card: 1 };
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background }, screen: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: spacing.xxl, paddingTop: spacing.lg, paddingBottom: 48 }, centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  logo: { fontFamily: typography.fontFamily.ui, fontSize: 38, letterSpacing: -2.4, fontWeight: '800', color: colors.primaryDark, marginBottom: spacing.xxxl }, title: { fontFamily: typography.fontFamily.ui, fontSize: typography.h2, lineHeight: 30, fontWeight: '700', color: colors.textPrimary, marginBottom: spacing.sm }, editorial: { fontFamily: typography.fontFamily.editorial, fontSize: typography.display, lineHeight: 43, fontWeight: '500', color: colors.textPrimary }, subtitle: { fontFamily: typography.fontFamily.ui, fontSize: typography.body, lineHeight: 25, color: colors.secondary, marginBottom: spacing.xxl }, label: { fontFamily: typography.fontFamily.ui, fontSize: typography.caption, fontWeight: '800', letterSpacing: 1.2, color: colors.secondary, marginBottom: spacing.sm, marginTop: spacing.xxl, textTransform: 'uppercase' },
  input: { fontFamily: typography.fontFamily.ui, backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, paddingHorizontal: spacing.lg, fontSize: typography.body, color: colors.textPrimary, minHeight: 54 }, button: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: spacing.lg, minHeight: 54, alignItems: 'center', justifyContent: 'center', marginTop: spacing.lg }, buttonText: { fontFamily: typography.fontFamily.ui, color: '#FFF', fontSize: typography.button, fontWeight: '700' }, secondaryButton: { borderColor: '#BBD3E7', borderWidth: 1, backgroundColor: colors.surface, borderRadius: radius.md, paddingHorizontal: spacing.lg, minHeight: 54, alignItems: 'center', justifyContent: 'center', marginTop: spacing.sm }, secondaryText: { fontFamily: typography.fontFamily.ui, color: colors.primary, fontSize: typography.button, fontWeight: '700' }, card: { backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.lg, marginBottom: spacing.lg, borderWidth: 1, borderColor: colors.border }, error: { fontFamily: typography.fontFamily.ui, color: colors.danger, marginTop: spacing.sm, lineHeight: 20 }, muted: { fontFamily: typography.fontFamily.ui, color: colors.secondary },
  chip: { borderRadius: radius.pill, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingVertical: 11, paddingHorizontal: 15, marginRight: 8, marginBottom: 8, minHeight: 44 }, chipSelected: { backgroundColor: '#D9EEFF', borderColor: colors.primary }, chipText: { fontFamily: typography.fontFamily.ui, color: colors.textPrimary, fontSize: 15 }, chipSelectedText: { fontFamily: typography.fontFamily.ui, color: colors.primaryDark, fontWeight: '700', fontSize: 15 }, nav: { flexDirection: 'row', borderTopWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, paddingHorizontal: 8, paddingTop: 8, paddingBottom: 10 }, navItem: { flex: 1, alignItems: 'center', padding: 8, minHeight: 60 }, navText: { fontFamily: typography.fontFamily.ui, color: colors.secondary, fontSize: 12, fontWeight: '600' }, navActive: { color: colors.primary, fontWeight: '800' }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, badge: { color: colors.success, fontWeight: '800', fontSize: typography.caption }, skeleton: { height: 80, backgroundColor: '#E3F0FA', borderRadius: radius.md, marginBottom: spacing.lg }, link: { fontFamily: typography.fontFamily.ui, color: colors.primary, fontWeight: '700', paddingVertical: 8, minHeight: 44 }, bullet: { fontFamily: typography.fontFamily.ui, color: colors.textPrimary, lineHeight: typography.lineHeight, marginBottom: 6 }, small: { fontFamily: typography.fontFamily.ui, fontSize: typography.bodySmall, color: colors.secondary }
});
