import React from 'react';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, Text, TextInput, View } from 'react-native';
import { colors, styles } from '../theme';
import { Icon } from './Icon';

export function Logo({ compact = false }: { compact?: boolean }) { return <Text accessibilityRole="image" accessibilityLabel="Newzi" style={[styles.logo, compact && { fontSize: 28, marginBottom: 0 }]}>newz<Text style={{ color: colors.newziBlue }}>i</Text></Text>; }
export function Button({ title, onPress, secondary = false, disabled = false }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({ pressed }) => [secondary ? styles.secondaryButton : styles.button, pressed && { opacity: .78 }, disabled && { opacity: .5 }]}><Text style={secondary ? styles.secondaryText : styles.buttonText}>{title}</Text></Pressable>; }
export function TextField({ label, value, onChangeText, ...props }: { label: string; value: string; onChangeText: (value: string) => void; [key: string]: unknown }) { return <View><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholderTextColor={colors.muted} {...props} style={styles.input} /></View>; }
export function Screen({ children, refresh, refreshing }: { children: React.ReactNode; refresh?: () => void; refreshing?: boolean }) { return <SafeAreaView style={styles.safe}><ScrollView style={styles.screen} contentContainerStyle={styles.content} refreshControl={refresh ? { refreshing: !!refreshing, onRefresh: refresh } as any : undefined}>{children}</ScrollView></SafeAreaView>; }
export const SafeScreen = Screen;
export function Card({ children, style }: { children: React.ReactNode; style?: any }) { return <View style={[styles.card, style]}>{children}</View>; }
export function SectionHeader({ children }: { children: React.ReactNode }) { return <Text style={styles.label}>{children}</Text>; }
export function Badge({ children, tone = 'success' }: { children: React.ReactNode; tone?: 'success'|'warning'|'error' }) { const palette = tone === 'success' ? [colors.successSurface, colors.success] : tone === 'warning' ? [colors.warningSurface, colors.warning] : [colors.dangerSurface, colors.danger]; return <View style={{ alignSelf: 'flex-start', borderRadius: 99, paddingHorizontal: 12, paddingVertical: 7, backgroundColor: palette[0] }}><Text style={{ color: palette[1], fontWeight: '700' }}>{children}</Text></View>; }
export function Chip({ children, selected, onPress, disabled }: { children: React.ReactNode; selected?: boolean; onPress?: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: !!selected, disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.chip, selected && styles.chipSelected, pressed && { opacity: .78 }, disabled && { opacity: .45 }]}>{selected && <Icon name="check" color={colors.primary} size={16} />}<Text style={selected ? styles.chipSelectedText : styles.chipText}>{children}</Text></Pressable>; }
export function LoadingState() { return <View style={styles.centered}><ActivityIndicator color={colors.primary} /></View>; }
export function Skeleton({ height = 96 }: { height?: number }) { return <View accessible accessibilityLabel="Carregando" style={[styles.skeleton, { height }]} />; }
export function EmptyState({ title, text, onRetry }: { title: string; text: string; onRetry?: () => void }) { return <View style={[styles.centered, { paddingVertical: 40 }]}><Text style={[styles.editorial, { fontSize: 28, lineHeight: 34, textAlign: 'center' }]}>{title}</Text><Text style={[styles.subtitle, { textAlign: 'center', marginTop: 12 }]}>{text}</Text>{onRetry && <Button title="Tentar novamente" secondary onPress={onRetry} />}</View>; }
export function ErrorState({ message }: { message: string }) { return <Text accessibilityRole="alert" style={styles.error}>{message}</Text>; }
export function OfflineState() { return <Card><Text style={[styles.subtitle, { marginBottom: 0 }]}>Você está offline. Tente novamente quando houver conexão.</Text></Card>; }
export function SourceChip({ label }: { label: string }) { return <View style={styles.chip}><Text style={styles.chipText}>{label}</Text></View>; }
